# Generated by Django 6.0.3 on 2026-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_delete_gamewebsites'),
        ('users', '0002_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_games',
            field=models.ManyToManyField(to='games.game'),
        ),
    ]
