# Generated by Django 6.0.3 on 2026-04-14 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('games', '0002_delete_gamewebsites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community', to='games.game'),
        ),
    ]
