# Generated by Django 6.0.3 on 2026-04-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='body',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
