# Generated by Django 6.0.3 on 2026-05-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_communitypost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
