# Generated by Django 6.0.3 on 2026-05-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_communitypost_media_type_communitypost_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='media_url',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='community_posts/'),
        ),
    ]
